import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import CookieYes from "./components/analytics/CookieYes";
import GoogleAnalytics from "./components/analytics/GoogleAnalytics";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "KulturKompasset",
    template: "KulturKompasset - %s",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/kk-symbol.svg",
    shortcut: "/kk-symbol.svg",
    apple: "/kk-symbol.svg",
  },
};

function isNewspaperEmbedPath(pathname: string): boolean {
  return (
    pathname === "/embed/na-carousel-v1" ||
    pathname.startsWith("/embed/na-carousel-v1/")
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const requestHeaders = await headers();
  const pathname = requestHeaders.get("x-kk-pathname") ?? "";
  const shouldIncludeAnalytics = !isNewspaperEmbedPath(pathname);

  return (
    <html lang="en">
      <head>{shouldIncludeAnalytics ? <CookieYes /> : null}</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {shouldIncludeAnalytics ? <GoogleAnalytics /> : null}
        {children}
      </body>
    </html>
  );
}
